// Source: F:/Games/Dayz/scripts/4_world/entities/firearms/fsm/events.c Source File
// Extracted from DayZ Code Explorer by Zeroy


enum WeaponEventID
{
    UNKNOWN,
    MECHANISM,
    TRIGGER,
    TRIGGER_JAM,
    TRIGGER_AUTO_START,
    TRIGGER_AUTO_END,
    LOAD1_BULLET,
    CONTINUOUS_LOADBULLET_START,
    CONTINUOUS_LOADBULLET_END,
    UNJAM,
    ATTACH_MAGAZINE,
    UNJAMMING_FAILED_TIMEOUT,
    UNJAMMING_TIMEOUT,
    DETACH_MAGAZINE,
    SWAP_MAGAZINE,
    HUMANCOMMAND_ACTION_FINISHED,
    HUMANCOMMAND_ACTION_ABORTED,
    RELOAD_TIMEOUT,
    DRY_FIRE_TIMEOUT,
    SET_NEXT_MUZZLE_MODE,
    ANIMATION_EVENT,
