// Source: F:/Games/Dayz/scripts/3_game/global/errormodulehandler/bioserrormodule.c Source File
// Extracted from DayZ Code Explorer by Zeroy


enum EBiosError
{
    OK,
    CANCEL
    BAD_PARAMETER,
    NOT_FOUND,
    NOT_IMPLEMENTED,
    PURCHASE_REQUIRED,
    NOT_ALLOWED,
    BANNED,
    LOGICAL,
    
    WRONG_RESPONSE_DATA,        
    
    SERVER_HEARTBEAT_SERVER_NOT_FOUND,
    SERVER_REGISTER_ALREADY_EXISTS,     
    
    REQUEST_CREATE_FAIL_XHR,
    REQUEST_SEND_FAIL,
    REQUEST_WAIT_FAIL,
    
    NON_JSON_RESPONSE,
    
    // RESERVED SPACE OF REDUNDANT ERRORS

    UPDATE_REQUIRED,
    UPDATE_REQUIRED_AND_DOWNLOADED,
    
    COMUNICATION_ERROR,

    UNKNOWN,
    
    BAD_SCRIPT,
    
    
    COMMUNICATION_TIMED_OUT,
    COMMUNICATION_RESET,
    COMMUNICATION_ABORTED
