// Source: F:/Games/Dayz/scripts/data/internal/script_console_hints.json Source File
// Extracted from DayZ Code Explorer by Zeroy

{
    &quot;WidgetHintBindings&quot;: {
        &quot;-1309929726&quot;: &quot;&quot;,
        &quot;552892759&quot;: &quot;Insert text to search for in currently opened Cfg file.&quot;,
        &quot;1985069064&quot;: &quot;Select a preset location to auto-set it for \&quot;TELEPORT\&quot; below.&quot;,
        &quot;885568265&quot;: &quot;Set Value for given weather parameter (0 - no clouds/rain/fog/snowfall, 1 - max). Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;462454794&quot;: &quot;Toggle which Cfg folders you&#39;d like to display below.&quot;,
        &quot;-545900616&quot;: &quot;&quot;,
        &quot;1629523981&quot;: &quot;Set in how many seconds the weather change is to be applied when confirmed with \&quot;APPLY\&quot;. Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;-1586623473&quot;: &quot;Toggle whether characters of other players are displayed on the map.&quot;,
        &quot;1525433266&quot;: &quot;Set radius at which items around character are displayed on the left.&quot;,
        &quot;-931449582&quot;: &quot;&quot;,
        &quot;1856235795&quot;: &quot;&quot;,
        &quot;1374152726&quot;: &quot;Apply set values to current weather.&quot;,
        &quot;435322647&quot;: &quot;&quot;,
        &quot;-1656896488&quot;: &quot;Set Z coordinate for teleportation.&quot;,
        &quot;-1374196455&quot;: &quot;Select a pre-made preset of character gear to spawn with item spawning buttons.&quot;,
        &quot;956118042&quot;: &quot;&quot;,
        &quot;474373214&quot;: &quot;&quot;,
        &quot;-1687161828&quot;: &quot;Copy name of selected sample to clipboard.&quot;,
        &quot;1728033821&quot;: &quot;Set in how many seconds the weather change is to be applied when confirmed with \&quot;APPLY\&quot;. Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;-1518723554&quot;: &quot;Select which Cfg folder or file you&#39;d like to expand or open.&quot;,
        &quot;1103406623&quot;: &quot;Toggle display of sickness agents. Adjust/toggle them with mouse cursor accessed wit LCtrl+9.&quot;,
        &quot;1192267296&quot;: &quot;Text Text&quot;,
        &quot;1251441442&quot;: &quot;Toggle display of character and environment temperature information.&quot;,
        &quot;-1253779744&quot;: &quot;Set current date (day).&quot;,
        &quot;1501371172&quot;: &quot;&quot;,
        &quot;-415538395&quot;: &quot;&quot;,
        &quot;-2109211354&quot;: &quot;Input script commands.&quot;,
        &quot;-140039896&quot;: &quot;Spawn multiple of currently selected item in rectangle shape on ground.&quot;,
        &quot;-1202987991&quot;: &quot;&quot;,
        &quot;-1272174379&quot;: &quot;Toggle whether model of selected item is shown in this window.&quot;,
        &quot;-1870929874&quot;: &quot;Set quantity (or amount of contents or internal energy) of item before spawning it. 0 - no quantity, 1 - full quantity.&quot;,
        &quot;957070895&quot;: &quot;Toggle to only display items of given group.&quot;,
        &quot;1603231024&quot;: &quot;Toggle to display only items of this group.&quot;,
        &quot;-1510880489&quot;: &quot;&quot;,
        &quot;-713944167&quot;: &quot;Spawn selected item in character&#39;s hands if they are free.&quot;,
        &quot;1645635891&quot;: &quot;&quot;,
        &quot;-926453058&quot;: &quot;Toggle to display only items of this group.&quot;,
        &quot;1946388278&quot;: &quot;Change current time by dragging the bar.&quot;,
        &quot;1721471763&quot;: &quot;Toggle to display only items of this group.&quot;,
        &quot;-880396485&quot;: &quot;Change order of listed items (ASVAL > HandSaw or HandSaw > ASVAL)&quot;,
        &quot;-1676706756&quot;: &quot;Set number of selected item to spawn in rectangle shape.&quot;,
        &quot;-1461226780&quot;: &quot;Set horizontal distance between items spawned in rectangle.&quot;,
        &quot;1032024897&quot;: &quot;Distance (in m) between character location and where the cursor is pointing on the map.&quot;,
        &quot;1978778377&quot;: &quot;Set in how many seconds the weather change is to be applied when confirmed with \&quot;APPLY\&quot;. Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;1220773699&quot;: &quot;Teleport character to current coordinates. XYZ row takes precedence if all are filled.&quot;,
        &quot;2034500375&quot;: &quot;Copy all current values to clipboard.&quot;,
        &quot;-1134570680&quot;: &quot;Set current date (month).&quot;,
        &quot;838830156&quot;: &quot;Toggle to display only items of this group.&quot;,
        &quot;356423951&quot;: &quot;Set current date (year).&quot;,
        &quot;1602614383&quot;: &quot;Set Value for given weather parameter (0 - no clouds/rain/fog/snowfall, 1 - max). Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;-846199983&quot;: &quot;Set sliders to values saved in clipboard by using \&quot;Copy\&quot; button.&quot;,
        &quot;810620243&quot;: &quot;&quot;,
        &quot;-1754572201&quot;: &quot;Set X coordinate for teleportation.&quot;,
        &quot;394215512&quot;: &quot;Set for how long the newly set weather will last in seconds when confirmed with \&quot;APPLY\&quot;. Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;-1667685287&quot;: &quot;&quot;,
        &quot;-1035546020&quot;: &quot;&quot;,
        &quot;1127520350&quot;: &quot;Remove created marks.&quot;,
        &quot;-1942116257&quot;: &quot;Display vertical red lines at positions of selected object.&quot;,
        &quot;1900960787&quot;: &quot;&quot;,
        &quot;-532831285&quot;: &quot;Toggle whether preset items will overwrite current gear (ON) or not (OFF) when spawned in inventory.&quot;,
        &quot;-1138959773&quot;: &quot;Play selected sample.&quot;,
        &quot;1071420364&quot;: &quot;Clear currently displayed prints above.&quot;,
        &quot;1568620390&quot;: &quot;Toggle which Cfg folders you&#39;d like to display below.&quot;,
        &quot;-204342681&quot;: &quot;Set Value for given weather parameter (0 - no clouds/rain/fog/snowfall, 1 - max). Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;74429288&quot;: &quot;Toggle to display only items of this group.&quot;,
        &quot;2035503977&quot;: &quot;&quot;,
        &quot;-958005142&quot;: &quot;Play selected sample in a loop.&quot;,
        &quot;522681359&quot;: &quot;&quot;,
        &quot;-154427780&quot;: &quot;Set current time (HH:MM).&quot;,
        &quot;-1808856209&quot;: &quot;Display all available actions for currently selected item.&quot;,
        &quot;-682218895&quot;: &quot;&quot;,
        &quot;-1603829646&quot;: &quot;Toggle display of executable and scripts versions.&quot;,
        &quot;1147728663&quot;: &quot;&quot;,
        &quot;1845530998&quot;: &quot;Set for how long the newly set weather will last in seconds when confirmed with \&quot;APPLY\&quot;. Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;-1676884696&quot;: &quot;Click on a sample to select it.&quot;,
        &quot;1560972410&quot;: &quot;Set distance (in m) at which the object will spawn from selected spawn point.&quot;,
        &quot;-1991846276&quot;: &quot;Toggle display of non-standard items. Avoid using this.&quot;,
        &quot;-530858371&quot;: &quot;&quot;,
        &quot;1284982144&quot;: &quot;Toggle display of current values of HeatComfort, Tremor, Wet, Energy, Water, Diet, Stamina, Specialty, BlodType, Toxicity, HeatBuffer, (naS)Immunity and (NaS)BrokenLegs.&quot;,
        &quot;719387520&quot;: &quot;&quot;,
        &quot;-1909562494&quot;: &quot;Insert text to search for selected sound samples.&quot;,
        &quot;483271299&quot;: &quot;Set Value for given weather parameter (0 - no clouds/rain/fog/snowfall, 1 - max). Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;2118108033&quot;: &quot;Add new preset location to teleport to.&quot;,
        &quot;-43811451&quot;: &quot;Toggle to display only items of this group.&quot;,
        &quot;1092731813&quot;: &quot;Toggle cursor in free camera (accessed with Home button).&quot;,
        &quot;-1695661183&quot;: &quot;Set vertical distance between items spawned in rectangle.&quot;,
        &quot;-2138518253&quot;: &quot;Spawn Special will spawn the item with attachments, e.g. complete car or weapon with magazine and optics.&quot;,
        &quot;1648767369&quot;: &quot;&quot;,
        &quot;-1998526418&quot;: &quot;Toggle to only display items of given group.&quot;,
        &quot;-145473140&quot;: &quot;&quot;,
        &quot;818197039&quot;: &quot;&quot;,
        &quot;-1690574705&quot;: &quot;Create new gear preset. Add items by selecting them on the left side and clicking >> on the right.&quot;,
        &quot;1503709840&quot;: &quot;Set current time (HH:MM).&quot;,
        &quot;-1809094665&quot;: &quot;Toggle to display only items of this group.&quot;,
        &quot;952377237&quot;: &quot;&quot;,
        &quot;-2050600298&quot;: &quot;Set X, Y, Z coordinates for teleportation. Doubleclick clears the field.&quot;,
        &quot;99191960&quot;: &quot;Click to place Pos marker. Doubleclick to teleport. Zoom with mousewheel. Drag by holding down RMB.&quot;,
        &quot;-1822479463&quot;: &quot;Spawn selected item at cursor location.&quot;,
        &quot;1793923379&quot;: &quot;Click on item that is part of selected preset to be able to spawn it independently.&quot;,
        &quot;-897245409&quot;: &quot;&quot;,
        &quot;1439738784&quot;: &quot;Text Text&quot;,
        &quot;-461088863&quot;: &quot;&quot;,
        &quot;1163341963&quot;: &quot;&quot;,
        &quot;-1280622026&quot;: &quot;&quot;,
        &quot;-1506294364&quot;: &quot;Click on item to select it and be able to spawn it.&quot;,
        &quot;1337846693&quot;: &quot;Set Value for given weather parameter (0 - no clouds/rain/fog/snowfall, 1 - max). Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;1964188584&quot;: &quot;Toggle display of current Immunity, Blood, Health, Energy and Water levels.&quot;,
        &quot;179964842&quot;: &quot;Set how many columns of given item will be spawned.&quot;,
        &quot;609446542&quot;: &quot;&quot;,
        &quot;-187054675&quot;: &quot;Spawn selected item on ground at current location.&quot;,
        &quot;-454700913&quot;: &quot;&quot;,
        &quot;-1813365845&quot;: &quot;Reset \&quot;Target Time\&quot; and \&quot;Duration\&quot; sliders to default.&quot;,
        &quot;415249808&quot;: &quot;&quot;,
        &quot;808583227&quot;: &quot;Displays items in vicinity and allows you to select one with LMB.&quot;,
        &quot;-1388139290&quot;: &quot;&quot;,
        &quot;-297078348&quot;: &quot;&quot;,
        &quot;-1639824201&quot;: &quot;&quot;,
        &quot;118816952&quot;: &quot;Set current time (HH:MM).&quot;,
        &quot;1395927373&quot;: &quot;Display details (parameters, states) of selected item on screen. Close the display with LCtrl+NumDel.&quot;,
        &quot;1937597885&quot;: &quot;&quot;,
        &quot;1114139070&quot;: &quot;Set radius (in m) at which selected item is affected by Mark Them In World.&quot;,
        &quot;-1400834881&quot;: &quot;Toggle display of character modifiers (states and diseases). Adjust them with cursor accessed with LCtrl+9.&quot;,
        &quot;-1538327821&quot;: &quot;Set Value for given weather parameter (0 - no clouds/rain/fog/snowfall, 1 - max). Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;559110851&quot;: &quot;&quot;,
        &quot;-1756742460&quot;: &quot;Set how many rows of selected item will be spawned.&quot;,
        &quot;1048985543&quot;: &quot;Toggle whether scripts.log is being generated.&quot;,
        &quot;980825486&quot;: &quot;Set health of item before spawning it (0 - RUINED, 1 - PRISTINE).&quot;,
        &quot;-1685056104&quot;: &quot;Toggle display of stomach contents of current character.&quot;,
        &quot;-553596725&quot;: &quot;Spawn selected item in inventory, if space is available.&quot;,
        &quot;583762636&quot;: &quot;&quot;,
        &quot;-309955634&quot;: &quot;Set currently selected preset as default. Avoid using this as it leads to an assert.&quot;,
        &quot;-1300817713&quot;: &quot;Stop playing selected sample.&quot;,
        &quot;-1725969712&quot;: &quot;Log currently selected parameter in script.log.&quot;,
        &quot;1062495443&quot;: &quot;Set in how many seconds the weather change is to be applied when confirmed with \&quot;APPLY\&quot;. Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;1782793173&quot;: &quot;&quot;,
        &quot;1674622165&quot;: &quot;Execute current script command.&quot;,
        &quot;-534593577&quot;: &quot;Input desired text to filter objects displayed below.&quot;,
        &quot;-2018753208&quot;: &quot;Toggle which Cfg folders you&#39;d like to display below.&quot;,
        &quot;-1690853926&quot;: &quot;Toggle to display only items of this group.&quot;,
        &quot;-927781&quot;: &quot;&quot;,
        &quot;-767715875&quot;: &quot;Displays output of ran script commands.&quot;,
        &quot;1308118751&quot;: &quot;Set the \&quot;Value\&quot; sliders to reflect current weather.&quot;,
        &quot;-1989414688&quot;: &quot;Toggle display of current coordinates and contents of clipboard.&quot;,
        &quot;-546292832&quot;: &quot;Toggle to display only items of this group.&quot;,
        &quot;-1480158432&quot;: &quot;&quot;,
        &quot;-808212319&quot;: &quot;Toggle to display only items of this group.&quot;,
        &quot;186781669&quot;: &quot;Coordinates of where the cursor is pointing on the map.&quot;,
        &quot;1434793702&quot;: &quot;Click to copy current Pos coordinates to clipboard\n\nUse shift to copy the position in raw format.&quot;,
        &quot;1612320230&quot;: &quot;&quot;,
        &quot;-1078487576&quot;: &quot;Set for how long the newly set weather will last in seconds when confirmed with \&quot;APPLY\&quot;. Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;-569113440&quot;: &quot;&quot;,
        &quot;2025665224&quot;: &quot;&quot;,
        &quot;-552641096&quot;: &quot;&quot;,
        &quot;-441110290&quot;: &quot;Remove previously created preset position.&quot;,
        &quot;2113763824&quot;: &quot;Toggle display of scriptExt.log output.&quot;,
        &quot;-1311957517&quot;: &quot;&quot;,
        &quot;-1835578635&quot;: &quot;&quot;,
        &quot;-587001353&quot;: &quot;Clear outputs field.&quot;,
        &quot;1840024830&quot;: &quot;&quot;,
        &quot;787439097&quot;: &quot;Copy name of currently selected item to clipboard.&quot;,
        &quot;-573218053&quot;: &quot;&quot;,
        &quot;-897661700&quot;: &quot;&quot;,
        &quot;2115342845&quot;: &quot;Current Pos marker coordinates (same as character coordinates when console is opened).&quot;,
        &quot;2050317772&quot;: &quot;Insert text to search only for specific Cfg folders and files.&quot;,
        &quot;1240759449&quot;: &quot;Spawn selected item in inventory of object currently being aimed at.&quot;,
        &quot;-627982573&quot;: &quot;Set Value for given weather parameter (0 - no clouds/rain/fog/snowfall, 1 - max). Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;-1605114403&quot;: &quot;Set in how many seconds the weather change is to be applied when confirmed with \&quot;APPLY\&quot;. Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;,
        &quot;316903752&quot;: &quot;Set for how long the newly set weather will last in seconds when confirmed with \&quot;APPLY\&quot;. Hold RMB and LMB to adjust values for all at once and automatically apply them. Hold SHIFT to automatically apply this value only.&quot;
    }
